#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-image-size-limit-help() {
  declare desc="help command"
  declare CMD="$1"
  local plugin_name="image-size-limit"
  local plugin_description="Limit allowed app image size during deployment"

  if [[ "$CMD" == "${plugin_name}:help" ]]; then
    echo -e "Usage: dokku ${plugin_name}[:COMMAND]"
    echo ''
    echo "$plugin_description"
    echo ''
    echo 'Available commands:'
    fn-help-content | sort | column -c2 -t -s,
  elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
    fn-help-content
  else
    cat <<help_desc
    $plugin_name, $plugin_description
help_desc
  fi
}

fn-help-content() {
  declare desc="return help content"
  cat <<help_content
    image-size-limit:report (<app>|--global), Check the current image size limit for an app or globally.
    image-size-limit:set (<app>|--global) bytes, Set the maximum allowed image size in bytes. Deployments that exceed this limit will be rejected. Default is 2GB.
    image-size-limit:help, Show help for the image-size-limit plugin
help_content
}
