#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/image-size-limit/functions"

cmd-image-size-limit-set() {
  declare desc="Set the maximum allowed image size in bytes. Deployments that exceed this limit will be rejected. Default is 2GB."
  declare cmd="image-size-limit:set"

  [[ "$1" == "image-size-limit:set" ]] || return 1

  local app_or_global="$2"
  local limit="$3"

  # if limit is provided, check if it's a number
  if [[ -n "$limit" && ! "$limit" =~ ^[0-9]+$ ]]; then
    echo "Limit must be an integer number of bytes"
    return 1
  fi

  if [[ "$app_or_global" == "--global" ]]; then
    if [[ -z "$limit" ]]; then
      DOKKU_QUIET_OUTPUT=1 config_unset --no-restart "$app_or_global" DOKKU_IMAGE_SIZE_LIMIT
      echo "Global image size limit unset"
      return 0
    fi
    DOKKU_QUIET_OUTPUT=1 config_set --no-restart "$app_or_global" DOKKU_IMAGE_SIZE_LIMIT="$limit"
    echo "Global image size limit set to $(fn-format-size "$limit")"
  else
    verify_app_name "$app_or_global"
    if [[ -z "$limit" ]]; then
      DOKKU_QUIET_OUTPUT=1 config_unset --no-restart "$app_or_global" DOKKU_IMAGE_SIZE_LIMIT
      echo "Image size limit for $app_or_global unset"
      return 0
    fi
    DOKKU_QUIET_OUTPUT=1 config_set --no-restart "$app_or_global" DOKKU_IMAGE_SIZE_LIMIT="$limit"
    echo "Image size limit for $app_or_global set to $(fn-format-size "$limit")"
  fi

  return 0
}

cmd-image-size-limit-set "$@"
